import { useRef, useState } from 'react';
import type { AppState } from '../domain/types';
import type { Command } from '../domain/workflow';
import { scenarios } from '../fixtures/scenarios';
import { calculateTax } from '../rules/tax';
import { exportState,importState,MAX_IMPORT_BYTES } from '../storage/store';
import { downloadBlob } from '../components/download';
import { Badge, Modal, rupiah } from '../components/Ui';

export function Learning({state,dispatch,onImport}:{state:AppState;dispatch:(c:Command)=>void;onImport:(s:AppState)=>Promise<void>}) {
  const [scenarioId,setScenarioId]=useState(state.scenarioId);const [confirmReset,setConfirmReset]=useState(false);
  const [answers,setAnswers]=useState(state.learning.answers);const [error,setError]=useState('');const [result,setResult]=useState('');
  const [price,setPrice]=useState('100000000');const [priceType,setPriceType]=useState('net');const [clock,setClock]=useState(state.clock);
  const fileRef=useRef<HTMLInputElement>(null); const scenario=scenarios.find(s=>s.id===state.scenarioId)??scenarios[0];
  const hints=['Mulai dari dokumen approved. PPN keluaran umum dihitung 12% × (11/12 × harga neto).','Hanya PM eligible dengan keputusan Kredit yang masuk ke SPT. PPnBM tidak dapat dikreditkan.','III.E = III.A − III.B − III.C − III.D. Kompensasi yang sah ikut dalam III.C. Pembayaran tidak mengubah hasil penghitungan KB.'];
  let calculation;let calculationError='';try{calculation=calculateTax({[priceType]:price,regime:'nonLuxury',transactionCode:'04'});}catch(e){calculationError=(e as Error).message;}
  return <><div className="page-header"><div><div className="eyebrow">LABORATORIUM PAJAK</div><h1>Belajar, coba, pahami</h1><p className="muted">Tiga mode, satu mesin hitung. Setiap perubahan tersimpan lokal.</p></div><Badge kind="blue">{state.mode}</Badge></div>
    <div className="mode-cards">{(['TERPANDU','MANDIRI','UJIAN'] as const).map((mode,i)=><button className={`mode-card ${state.mode===mode?'selected':''}`} key={mode} onClick={()=>dispatch({type:'SET_MODE',mode})}><span className="mode-icon">{['◈','◇','▤'][i]}</span><b>{['Terpandu','Mandiri','Ujian'][i]}</b><small>{['Ikuti urutan dengan petunjuk bertahap.','Jelajahi alur dan periksa hasil sendiri.','Selesaikan kasus tanpa hint, lalu nilai jawaban.'][i]}</small></button>)}</div>
    <section className="panel"><div className="panel-title"><h2>Kasus aktif · {scenario.title}</h2><Badge>DESIGN · fixture deterministik</Badge></div><div className="panel-body"><p>{state.mode === 'UJIAN' ? ({kb:'Penjualan Rp500 juta; pembelian eligible Rp200 juta; kompensasi September Rp3 juta. Hitung hasil SPT dan selesaikan alurnya.',lb:'Penjualan Rp100 juta dan pembelian eligible Rp250 juta. Hitung hasil dan sampaikan SPT.',nihil:'Penjualan dan pembelian eligible masing-masing Rp200 juta. Hitung hasil dan sampaikan SPT.',ppnbm:'ASSUMPTION: produsen BKP sah tergolong mewah, harga Rp1 miliar, PPnBM latihan20%, PM Rp22 juta. Hitung PPN dan PPnBM secara terpisah.',noneligible:'Penjualan Rp500 juta; total PM Rp22 juta tetapi Rp5 juta tidak eligible; kompensasi Rp3 juta. Tentukan hasil SPT.',compensation:'LB Oktober Rp200 ribu direvisi menjadi Rp100 ribu; LB November Rp300 ribu diteruskan ke Desember. Tentukan kompensasi Desember.'}[scenario.id] ?? scenario.title) : scenario.description}</p><div className="form-grid"><div className="field"><label htmlFor="scenario">Pilih kasus untuk replay / reset</label><select id="scenario" value={scenarioId} onChange={e=>setScenarioId(e.target.value)}>{scenarios.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></div><div className="field field-action"><button className="button" onClick={()=>setConfirmReset(true)}>Mulai ulang kasus</button></div></div><p className="hint">Reset mengganti progres dengan fixture terpilih dalam satu transaksi. Ekspor progres terlebih dahulu bila ingin menyimpannya.</p>{state.mode!=='UJIAN'&&<div className="learning-tasks">{scenario.tasks.map((task,i)=><div key={task}><span>{String(i+1).padStart(2,'0')}</span>{task}</div>)}</div>}
      {state.mode!=='UJIAN'&&<div className="hint-box"><button className="button" disabled={state.learning.hints>=3} onClick={()=>dispatch({type:'HINT'})}>Buka petunjuk berikutnya ({Math.min(state.learning.hints,3)}/3)</button>{hints.slice(0,state.learning.hints).map((h,i)=><p key={h}><b>Petunjuk {i+1}.</b> {h}</p>)}</div>}</div></section>
    <div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>Periksa pemahaman</h2></div><form className="panel-body" onSubmit={e=>{e.preventDefault();dispatch({type:'GRADE',answers});}}><p>Masukkan hasil dasar kasus sebelum perubahan transaksi tambahan. Nilai ini menilai tiga jawaban; penyelesaian workflow dilihat pada riwayat.</p><div className="field"><label htmlFor="answer-ppn">Hasil PPN (rupiah tanpa pemisah, LB negatif)</label><input id="answer-ppn" inputMode="decimal" value={answers.ppn??''} onChange={e=>setAnswers({...answers,ppn:e.target.value})} placeholder="Contoh: 30000000" required/></div><div className="field"><label htmlFor="answer-ppnbm">Hasil PPnBM (rupiah tanpa pemisah)</label><input id="answer-ppnbm" inputMode="decimal" value={answers.ppnbm??''} onChange={e=>setAnswers({...answers,ppnbm:e.target.value})} required/></div><div className="field"><label htmlFor="answer-status">Status penghitungan</label><select id="answer-status" value={answers.status??''} onChange={e=>setAnswers({...answers,status:e.target.value})} required><option value="">Pilih status</option><option>KB</option><option>LB</option><option>NIHIL</option></select></div><button className="button primary">Nilai jawaban</button>{state.learning.lastScore!==null&&<div className="score-result" role="status"><strong>{state.learning.lastScore}<small>/100</small></strong><div><b>{state.learning.lastScore===100?'Ketiga jawaban sesuai.':'Periksa kembali jawaban Anda.'}</b><p>Target: PPN {rupiah(scenario.expectedVat)}, PPnBM {rupiah(scenario.expectedLuxury)}, status {scenario.expectedStatus}. Percobaan {state.learning.attempts}.</p></div></div>}</form></section>
    <section className="panel"><div className="panel-title"><h2>Telusuri formula</h2><Badge>PMK 131/2024</Badge></div><div className="panel-body">{state.mode==='UJIAN'?<p className="notice">Kalkulator dan hint disembunyikan selama ujian. Mesin hitung pada dokumen tetap sama.</p>:<><div className="field"><label htmlFor="price-type">Jenis harga</label><select id="price-type" value={priceType} onChange={e=>setPriceType(e.target.value)}><option value="net">Sebelum pajak (neto)</option><option value="gross">Termasuk PPN (bruto)</option></select></div><div className="field"><label htmlFor="lab-price">Harga rupiah tanpa pemisah ribuan</label><input id="lab-price" value={price} inputMode="decimal" onChange={e=>setPrice(e.target.value)}/></div>{calculation?<dl className="formula-list"><div><dt>Harga neto{priceType==='gross'?' = bruto ÷ 1,11':''}</dt><dd>{rupiah(calculation.net)}</dd></div><div><dt>DPP nilai lain = 11/12 × neto</dt><dd className="decimal-value">{Number(calculation.dpp).toLocaleString('id-ID',{maximumFractionDigits:6})}</dd></div><div><dt>PPN = 12% × DPP</dt><dd>{rupiah(calculation.vat)}</dd></div><div><dt>Total tagihan</dt><dd>{rupiah(calculation.total)}</dd></div></dl>:<p className="notice error">{calculationError}</p>}<p className="hint">DPP pecahan tidak dibulatkan terlebih dahulu. Aturan rupiah penuh diterapkan pada hasil PPN SPT. Kesamaan seluruh pembulatan faktur produksi belum diverifikasi.</p></>}</div></section></div>
    <section className="panel"><div className="panel-title"><h2>Progres & waktu simulasi</h2></div><div className="panel-body"><div className="toolbar"><button className="button" onClick={()=>downloadBlob(new Blob([exportState(state)],{type:'application/json'}),'SIM-progres-coretax.json')}>↓ Ekspor progres</button><button className="button" onClick={()=>fileRef.current?.click()}>↑ Impor progres</button><input className="sr-only" type="file" accept=".json,application/json" aria-label="Berkas progres simulasi" ref={fileRef} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setError('');setResult('');try{if(file.size>MAX_IMPORT_BYTES)throw new Error('Berkas maksimal 5 MB.');const restored=importState(await file.text());await onImport(restored);setResult('Progres berhasil diimpor secara atomik.');}catch(err){setError((err as Error).message);}e.target.value='';}}/></div><p className="hint">Berkas JSON berlabel simulasi memuat dokumen dan audit latihan. Impor hanya menerima schema yang dikenali; kegagalan tidak menghapus progres lama.</p><div className="form-grid"><div className="field"><label htmlFor="simulation-clock">Clock simulasi (ISO, zona waktu wajib)</label><input id="simulation-clock" value={clock} onChange={e=>setClock(e.target.value)}/></div><div className="field field-action"><button className="button" onClick={()=>dispatch({type:'SET_CLOCK',clock})}>Atur waktu latihan</button></div></div><p className="hint">Baseline: 15 November 2026, 09.00 WIB. Waktu ini fixture; tidak mengikuti jam komputer. Jatuh tempo nominal belum disesuaikan kalender hari libur resmi.</p>{error&&<p className="notice error" role="alert">{error}</p>}{result&&<p className="notice success" role="status">{result}</p>}</div></section>
    <section className="panel"><div className="panel-title"><h2>Replay riwayat tindakan</h2><Badge>{state.audit.filter(a=>a.actingTaxpayerId===state.actingTaxpayerId).length} event</Badge></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Waktu simulasi</th><th>Aktor</th><th>WP aktif</th><th>Tindakan</th><th>Objek</th></tr></thead><tbody>{state.audit.filter(a=>a.actingTaxpayerId===state.actingTaxpayerId).slice().reverse().map(a=><tr key={a.id}><td>{a.at}</td><td>{a.actorUserId}</td><td>{a.actingTaxpayerId}</td><td>{a.action}</td><td className="mono">{a.objectId}</td></tr>)}</tbody></table></div></section>
    {confirmReset&&<Modal title="Mulai ulang latihan?" onClose={()=>setConfirmReset(false)}><p>Semua dokumen, pembayaran, dan progres aktif akan diganti dengan kasus <b>{scenarios.find(s=>s.id===scenarioId)?.title}</b>. Ini hanya mengubah data latihan di browser ini.</p><div className="toolbar"><button className="button" onClick={()=>setConfirmReset(false)}>Batal</button><button className="button primary" onClick={()=>{dispatch({type:'RESET',scenarioId});setConfirmReset(false);}}>Reset atomic & mulai ulang</button></div></Modal>}
  </>;
}
