import { useEffect, useState } from 'react';
import Decimal from 'decimal.js';
import { Link } from 'react-router-dom';
import type { AppState, Billing, TaxReturnVersion } from '../domain/types';
import { availableDeposit, needsRepost, type Command } from '../domain/workflow';
import { isBillingExpired } from '../rules/tax';
import { downloadDocument } from '../components/download';
import { localTime, returnName, returnStatus, rupiah, wholeSum } from './returnDisplay';

interface Props { state: AppState; dispatch: (command: Command) => void; ledger?: boolean }

/** Asia/Jakarta is UTC+07:00; normalize instants before feeding timezone-less HTML inputs. */
export function toJakartaDateTimeInput(instant: string): string {
  return new Date(Date.parse(instant) + 7 * 60 * 60 * 1000).toISOString().slice(0, 16);
}
function outstanding(state: AppState, item: TaxReturnVersion, bucket: Billing['bucket']): string {
  const family = new Set(state.returns.filter(version => version.taxpayerId === item.taxpayerId && version.period === item.period).map(version => version.id));
  const paid = wholeSum(state.payments.filter(payment => payment.taxpayerId === item.taxpayerId && family.has(payment.returnId) && payment.bucket === bucket).map(payment => payment.amount));
  return Decimal.max(0, new Decimal(bucket === 'PPN' ? item.amounts.III_E : item.amounts.VI_C).minus(paid).plus(bucket === 'PPN' ? item.refundVat : item.refundLuxury)).toFixed(0);
}
function billingLabel(state: AppState, billing: Billing): string {
  return billing.status === 'PAID' ? 'Lunas' : billing.status === 'CANCELLED' ? 'Dibatalkan' : isBillingExpired(billing.issuedAt, state.clock) ? 'Kedaluwarsa' : 'Aktif — belum dibayar';
}

export function Payments({ state, dispatch, ledger = false }: Props) {
  const [selectedId, setSelectedId] = useState('');
  const [depositAmount, setDepositAmount] = useState('30000000');
  const [depositSource, setDepositSource] = useState('Setoran latihan mahasiswa');
  const [filter, setFilter] = useState('ALL');
  const [page, setPage] = useState(0);
  const [ledgerFilter, setLedgerFilter] = useState('ALL');
  const [clockValue, setClockValue] = useState(toJakartaDateTimeInput(state.clock));
  useEffect(() => { setClockValue(toJakartaDateTimeInput(state.clock)); }, [state.clock]);
  useEffect(() => { setSelectedId(''); setDepositSource('Setoran latihan mahasiswa'); setDepositAmount('30000000'); setPage(0); }, [state.actingTaxpayerId]);
  const ownReturns = state.returns.filter(item => item.taxpayerId === state.actingTaxpayerId).sort((a, b) => b.period.localeCompare(a.period) || b.version - a.version);
  const selected = ownReturns.find(item => item.id === selectedId) ?? ownReturns.find(item => item.status === 'AWAITING_PAYMENT') ?? ownReturns.find(item => item.status !== 'FILED') ?? ownReturns[0];
  const billings = state.billings.filter(item => item.taxpayerId === state.actingTaxpayerId);
  const payments = state.payments.filter(item => item.taxpayerId === state.actingTaxpayerId);
  const deposits = state.deposits.filter(item => item.taxpayerId === state.actingTaxpayerId);
  const allocations = state.allocations.filter(item => item.taxpayerId === state.actingTaxpayerId);
  const entries = state.ledger.filter(item => item.taxpayerId === state.actingTaxpayerId && (ledgerFilter === 'ALL' || item.kind === ledgerFilter));
  const taxpayer = state.taxpayers.find(item => item.id === state.actingTaxpayerId);
  const filtered = billings.filter(billing => filter === 'ALL' || (filter === 'EXPIRED' ? billing.status === 'ACTIVE' && isBillingExpired(billing.issuedAt, state.clock) : filter === 'ACTIVE' ? billing.status === 'ACTIVE' && !isBillingExpired(billing.issuedAt, state.clock) : billing.status === filter));
  const currentPage = Math.min(page, Math.max(0, Math.ceil(filtered.length / 10) - 1));
  const rows = filtered.slice(currentPage * 10, currentPage * 10 + 10);
  const balance = availableDeposit(state);
  const newClock = (issuedAt: string, offset: number) => dispatch({ type: 'SET_CLOCK', clock: new Date(Date.parse(issuedAt) + offset).toISOString() });
  return <div>
    <div className="page-header"><div><p className="eyebrow">{ledger ? 'Buku Besar' : 'Pembayaran'}</p><h1>{ledger ? 'Buku Besar Wajib Pajak' : 'Pembayaran & deposit'}</h1><p>{taxpayer?.name} · seluruh transaksi merupakan simulasi lokal.</p></div><span className="badge">DESIGN · tanpa layanan bank / MPN</span></div>
    <div className="notice"><strong>Waktu simulasi: {localTime(state.clock)} WIB.</strong> Billing berlaku 336 jam sejak diterbitkan dan belum berarti lunas. Membayar SPT KB tidak mengubah hasil penghitungan menjadi nihil.</div>
    <div className="metrics"><section className="panel"><p>Deposit tersedia</p><h2>{rupiah(balance)}</h2><small>Setoran dikurangi seluruh alokasi WP aktif</small></section><section className="panel"><p>Pembayaran simulasi tercatat</p><h2>{rupiah(wholeSum(payments.map(item => item.amount)))}</h2><small>{payments.length} catatan pembayaran · tidak ada uang nyata</small></section><section className="panel"><p>Billing aktif</p><h2>{billings.filter(item => item.status === 'ACTIVE' && !isBillingExpired(item.issuedAt, state.clock)).length}</h2><small>Pajak PPN dan PPnBM dipisahkan</small></section></div>
    {ledger ? <>
      <section className="panel"><div className="toolbar"><h2>Riwayat transaksi</h2><label className="field">Jenis transaksi<select value={ledgerFilter} onChange={event => setLedgerFilter(event.target.value)}><option value="ALL">Semua jenis</option><option value="DEPOSIT">Deposit</option><option value="PAYMENT">Pembayaran</option><option value="LIABILITY">Kewajiban SPT</option><option value="COMPENSATION">Kompensasi</option><option value="ADJUSTMENT">Penyesuaian</option></select></label></div><p className="notice">Debit / kredit di bawah adalah pencatatan belajar per kategori. Tidak dijumlahkan menjadi satu saldo lintas deposit, kompensasi, dan kewajiban. Catatan asal dan relasi dipertahankan.</p><div className="table-scroll"><table className="data-table"><thead><tr><th>Tanggal simulasi</th><th>Jenis</th><th>Uraian</th><th>Debit</th><th>Kredit</th><th>Referensi asal</th></tr></thead><tbody>{entries.map(entry => <tr key={entry.id}><td>{localTime(entry.date)}</td><td>{entry.kind}</td><td>{entry.description}</td><td className="numeric">{rupiah(entry.debit)}</td><td className="numeric">{rupiah(entry.credit)}</td><td>{entry.referenceId}</td></tr>)}{entries.length === 0 && <tr><td colSpan={6}>Belum ada transaksi pada filter ini.</td></tr>}</tbody></table></div></section>
      <section className="panel"><h2>Jejak audit WP aktif</h2><p>Pelaku dan WP yang diwakili dicatat terpisah; waktu mengikuti clock latihan.</p><div className="table-scroll"><table className="data-table"><thead><tr><th>Waktu</th><th>Aktor</th><th>WP yang diwakili</th><th>Tindakan</th><th>Objek</th></tr></thead><tbody>{state.audit.filter(item => item.actingTaxpayerId === state.actingTaxpayerId).slice(-30).reverse().map(event => <tr key={event.id}><td>{localTime(event.at)}</td><td>{state.users.find(user => user.id === event.actorUserId)?.name ?? event.actorUserId}</td><td>{event.actingTaxpayerId}</td><td>{event.action}</td><td>{event.objectId}</td></tr>)}</tbody></table></div><p>Menampilkan hingga 30 peristiwa terakhir. Ekspor progres menyimpan seluruh audit.</p></section>
    </> : <>
      <section className="panel"><h2>Bayar dan Lapor SPT</h2><label className="field">SPT yang dipilih<select value={selected?.id ?? ''} onChange={event => setSelectedId(event.target.value)}>{ownReturns.map(item => <option key={item.id} value={item.id}>{returnName(item)} — {returnStatus[item.status]}</option>)}{ownReturns.length === 0 && <option value="">Belum ada SPT</option>}</select></label>
        {selected ? <><div className="toolbar"><span className="badge">{returnStatus[selected.status]}</span><strong>Sisa PPN: {rupiah(outstanding(state, selected, 'PPN'))}</strong><strong>Sisa PPnBM: {rupiah(outstanding(state, selected, 'PPNBM'))}</strong></div>{needsRepost(state, selected) && selected.status !== 'FILED' && <div className="notice">Konsep belum diposting atau sumber telah berubah. Kembali ke SPT, periksa dokumen, lalu posting. Billing aktif perlu dibatalkan sebelum posting ulang.</div>}<div className="toolbar">{selected.status === 'POSTED' && <button className="button primary" onClick={() => dispatch({ type: 'PREPARE_PAYMENT', returnId: selected.id })}>Bayar dan Lapor</button>}{selected.status === 'AWAITING_PAYMENT' && <>{(['PPN', 'PPNBM'] as const).map(bucket => { const active = billings.some(billing => billing.returnId === selected.id && billing.bucket === bucket && billing.status === 'ACTIVE' && !isBillingExpired(billing.issuedAt, state.clock)); return new Decimal(outstanding(state, selected, bucket)).gt(0) && <button key={bucket} className="button primary" disabled={active || needsRepost(state, selected)} onClick={() => dispatch({ type: 'CREATE_BILLING', returnId: selected.id, bucket })}>{active ? `Billing ${bucket === 'PPNBM' ? 'PPnBM' : 'PPN'} aktif tersedia` : `Buat billing ${bucket === 'PPNBM' ? 'PPnBM' : 'PPN'}`}</button>; })}<button className="button" onClick={() => dispatch({ type: 'PAY_DEPOSIT', returnId: selected.id })}>Lunasi seluruh SPT dengan deposit</button></>}<Link className="button" to="/spt">{selected.status === 'READY' ? 'Lanjut tanda tangan & lapor' : 'Buka SPT'}</Link></div><p className="notice">Deposit harus cukup untuk <strong>seluruh kewajiban</strong> SPT. Gabungan sebagian deposit dan sebagian billing tidak didukung dalam baseline latihan. PPN dan PPnBM tetap memiliki alokasi terpisah. Setelah lunas, lanjutkan pelaporan untuk mendapatkan BPE.</p></> : <p>Buat konsep SPT pada menu Surat Pemberitahuan.</p>}
      </section>
      <section className="panel"><div className="toolbar"><h2>Daftar kode billing</h2><label className="field">Status billing<select value={filter} onChange={event => { setFilter(event.target.value); setPage(0); }}><option value="ALL">Semua</option><option value="ACTIVE">Aktif</option><option value="EXPIRED">Kedaluwarsa</option><option value="PAID">Lunas</option><option value="CANCELLED">Dibatalkan</option></select></label></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Kode billing simulasi</th><th>SPT / pajak</th><th>Jumlah</th><th>Terbit</th><th>Berlaku sampai</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>{rows.map(billing => { const expired = isBillingExpired(billing.issuedAt, state.clock); const item = ownReturns.find(version => version.id === billing.returnId); return <tr key={billing.id}><td>{billing.number}</td><td>{item ? returnName(item) : billing.returnId}<br />{billing.bucket}</td><td className="numeric">{rupiah(billing.amount)}</td><td>{localTime(billing.issuedAt)}</td><td>{localTime(billing.expiresAt)} WIB</td><td><span className="badge">{billingLabel(state, billing)}</span></td><td><div className="toolbar">{billing.status === 'ACTIVE' && <><button className="button primary" disabled={expired} onClick={() => dispatch({ type: 'PAY_BILLING', billingId: billing.id })} aria-label={`Bayar simulasi ${billing.number}`}>Bayar simulasi</button><button className="button" onClick={() => dispatch({ type: 'CANCEL_BILLING', billingId: billing.id })} aria-label={`Batalkan ${billing.number}`}>Batalkan billing</button></>}{billing.status === 'PAID' && <span>Pembayaran final; tidak dapat dibayar ulang.</span>}{billing.status === 'CANCELLED' && <span>Kembali ke konsep → Bayar dan Lapor → buat billing baru.</span>}</div>{billing.status === 'ACTIVE' && <details><summary>Uji batas 336 jam</summary><button className="button" onClick={() => newClock(billing.issuedAt, (335 * 60 + 59) * 60000)}>Atur clock 335 jam 59 menit</button><button className="button" onClick={() => newClock(billing.issuedAt, 336 * 3600000)}>Atur clock tepat 336 jam</button><p>Hanya mengubah waktu simulasi, bukan waktu sistem.</p></details>}</td></tr>; })}{rows.length === 0 && <tr><td colSpan={7}>Tidak ada billing. Posting SPT, pilih Bayar dan Lapor, kemudian terbitkan billing sesuai bucket pajak.</td></tr>}</tbody></table></div><div className="toolbar"><span>{filtered.length} billing · halaman {currentPage + 1} dari {Math.max(1, Math.ceil(filtered.length / 10))}</span><button className="button" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>Sebelumnya</button><button className="button" disabled={(currentPage + 1) * 10 >= filtered.length} onClick={() => setPage(currentPage + 1)}>Berikutnya</button></div><p>Kedaluwarsa tepat pada 336 jam. Batalkan billing kedaluwarsa, kembali ke konsep, lalu terbitkan ulang. Riwayat tetap tersimpan; billing lunas tidak dapat dihapus.</p></section>
      <section className="panel"><h2>Deposit pajak — latihan</h2><form className="form-grid" onSubmit={event => { event.preventDefault(); dispatch({ type: 'ADD_DEPOSIT', amount: depositAmount, source: depositSource }); }}><label className="field">Jumlah deposit sintetis (Rp)<input required inputMode="numeric" value={depositAmount} onChange={event => setDepositAmount(event.target.value)} pattern="[0-9]+" /></label><label className="field">Asal deposit latihan<input required value={depositSource} onChange={event => setDepositSource(event.target.value)} maxLength={150} /></label><button className="button" type="submit">Tambah deposit simulasi</button></form><p>Tanpa transfer bank. Asal setiap lot dan alokasi pembayaran disimpan.</p><div className="table-scroll"><table className="data-table"><thead><tr><th>Lot deposit</th><th>Tanggal</th><th>Asal</th><th>Setoran</th><th>Terpakai</th><th>Sisa</th></tr></thead><tbody>{deposits.map(lot => { const used = wholeSum(allocations.filter(item => item.depositId === lot.id).map(item => item.amount)); return <tr key={lot.id}><td>{lot.id}</td><td>{localTime(lot.date)}</td><td>{lot.source}</td><td className="numeric">{rupiah(lot.amount)}</td><td className="numeric">{rupiah(used)}</td><td className="numeric">{rupiah(new Decimal(lot.amount).minus(used).toFixed(0))}</td></tr>; })}{deposits.length === 0 && <tr><td colSpan={6}>Belum ada deposit.</td></tr>}</tbody></table></div></section>
    </>}
    <section className="panel"><h2>Bukti pembayaran simulasi</h2><div className="table-scroll"><table className="data-table"><thead><tr><th>Nomor pembayaran</th><th>Waktu</th><th>Pajak</th><th>Metode</th><th>Jumlah</th><th>Bukti</th></tr></thead><tbody>{payments.map(payment => { const receipt = state.receipts.find(item => item.taxpayerId === state.actingTaxpayerId && item.type === 'PAYMENT' && item.objectId === payment.id); return <tr key={payment.id}><td>{payment.id}</td><td>{localTime(payment.date)}</td><td>{payment.bucket}</td><td>{payment.method === 'DEPOSIT' ? 'Alokasi deposit' : 'Billing simulasi'}</td><td className="numeric">{rupiah(payment.amount)}</td><td>{receipt ? <button className="button" onClick={() => downloadDocument('Bukti Pembayaran — SIMULASI', receipt.number, `SIMULASI BELAJAR • BUKAN LAYANAN DJP\nNomor bukti: ${receipt.number}\nWP sintetis: ${taxpayer?.name}\nNPWP sintetis: ${taxpayer?.npwp}\nSPT: ${payment.returnId}\nPajak: ${payment.bucket}\nMetode: ${payment.method}\nJumlah: ${rupiah(payment.amount)}\nWaktu simulasi: ${localTime(payment.date)} WIB\nTidak ada uang nyata, bank, MPN, atau validasi DJP yang terlibat.\nDokumen ini tidak sah untuk administrasi perpajakan.`)}>Unduh bukti simulasi</button> : <span>Bukti historis fixture tidak tersedia.</span>}</td></tr>; })}{payments.length === 0 && <tr><td colSpan={6}>Bukti hanya muncul sesudah pembayaran simulasi tercatat.</td></tr>}</tbody></table></div></section>
    <section className="panel"><details><summary>Kontrol clock simulasi (WIB)</summary><form className="toolbar" onSubmit={event => { event.preventDefault(); dispatch({ type: 'SET_CLOCK', clock: `${clockValue}:00+07:00` }); }}><label className="field">Waktu fixture dalam WIB<input type="datetime-local" required value={clockValue} onChange={event => setClockValue(event.target.value)} /></label><button className="button" type="submit">Terapkan clock latihan</button></form><p>Tampilan tanggal pembayaran memakai Asia/Jakarta (UTC+7). Default fixture 15 November 2026; tanggal ini bukan tanggal aktual.</p></details></section>
  </div>;
}
