import { Link } from 'react-router-dom';
import Decimal from 'decimal.js';
import type { AppState } from '../domain/types';
import { currentReturn, type Command } from '../domain/workflow';
import { scenarios } from '../fixtures/scenarios';
import { rupiah, Badge } from '../components/Ui';

export function Portal({state}:{state:AppState;dispatch:(c:Command)=>void}) {
  const user=state.users.find(u=>u.id===state.actorUserId)!;
  const wp=state.taxpayers.find(w=>w.id===state.actingTaxpayerId)!;
  const scenario=scenarios.find(s=>s.id===state.scenarioId)??scenarios[0];
  const invoices=state.invoices.filter(i=>i.taxpayerId===wp.id);
  const spt=currentReturn(state);
  const steps=[{n:'01',title:'Periksa faktur',detail:'Tinjau transaksi dan rincian PPN',to:'/efaktur',done:invoices.some(i=>i.direction==='OUTPUT'&&i.status==='APPROVED')},{n:'02',title:'Tentukan Pajak Masukan',detail:'Periksa kelayakan pengkreditan',to:'/efaktur?tab=input',done:state.decisions.some(d=>d.taxpayerId===wp.id&&d.decision==='CREDIT')},{n:'03',title:'Posting & periksa SPT',detail:'Telusuri lampiran ke Induk',to:'/spt',done:!!spt&&spt.status!=='DRAFT'},{n:'04',title:'Bayar dan lapor',detail:'Selesaikan hingga BPE simulasi',to:'/spt',done:spt?.status==='FILED'}];
  const total=(direction:'INPUT'|'OUTPUT')=>invoices.filter(i=>i.direction===direction&&i.status==='APPROVED').reduce((sum,i)=>sum.plus(i.vat),new Decimal(0)).toString();
  return <><div className="page-header"><div><div className="eyebrow">PORTAL SAYA</div><h1>Selamat datang, {user.name.split(' ')[0]}</h1><p className="muted">Ruang kerja perpajakan Anda, dengan tempat untuk belajar.</p></div><Link className="button" to="/belajar">Panduan latihan <span>↗</span></Link></div>
    <div className="portal-banner"><div><span className="eyebrow">LATIHAN PPN & PPNBM</span><h2>Satu masa pajak.<br/>Pahami seluruh alurnya.</h2><p>Mulai dari faktur, susun SPT, lalu lihat bagaimana<br className="desktop-only"/> pembayaran dan pelaporan saling terhubung.</p><Link className="button gold" to="/efaktur">Mulai dari e-Faktur <span>→</span></Link></div><div className="banner-document" aria-hidden="true"><div className="paper"><div className="paper-title">SPT MASA PPN</div><i/><i/><i/><div className="paper-sum">12% × DPP</div><div className="paper-stamp">SIMULASI</div></div><span className="banner-circle">✓</span></div><div className="banner-meta"><span>MASA PAJAK</span><b>{state.scenarioId==='compensation'?'Desember 2026':'Oktober 2026'}</b><small>Waktu latihan · {new Date(state.clock).toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Jakarta'})}</small></div></div>
    <div className="stats-grid"><div className="stat"><span>Pajak Keluaran · dokumen disetujui</span><strong>{rupiah(total('OUTPUT'))}</strong><small>{invoices.filter(i=>i.direction==='OUTPUT').length} faktur keluaran pada WP aktif</small></div><div className="stat"><span>Pajak Masukan · sebelum keputusan</span><strong>{rupiah(total('INPUT'))}</strong><small>Kredit ditentukan melalui pemeriksaan dokumen</small></div><div className="stat emphasized"><span>{state.mode==='UJIAN'?'Mode ujian · hitung hasil Anda':`Target latihan · ${scenario.expectedStatus}`}</span><strong>{wp.type==='PKP'&&state.mode!=='UJIAN'?rupiah(scenario.expectedVat):'—'}</strong><small>{scenario.title} · target PPN, sebelum pembayaran</small></div></div>
    <div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>Alur belajar Anda</h2><Badge kind="blue">{steps.filter(s=>s.done).length} dari 4 tahap</Badge></div><div className="workflow-steps">{steps.map(s=><Link to={s.to} className="workflow-step" key={s.n}><span className={`step-number ${s.done?'complete':''}`}>{s.done?'✓':s.n}</span><span><b>{s.title}</b><small>{s.detail}</small></span><span className="step-arrow">›</span></Link>)}</div><div className="panel-foot">Status tahap mencerminkan data saat ini. Mode ujian dinilai secara terpisah.</div></section>
    <section className="panel"><div className="panel-title"><h2>Identitas wajib pajak</h2><Badge>Data sintetis</Badge></div><dl className="identity-list"><div><dt>Nama</dt><dd>{wp.name}</dd></div><div><dt>NPWP latihan</dt><dd className="mono">{wp.npwp}</dd></div><div><dt>Status</dt><dd>{wp.type==='PKP'?'Badan · Pengusaha Kena Pajak':'Orang pribadi · profil latihan'}</dd></div><div><dt>Pengguna aktif</dt><dd>{user.name}</dd></div></dl><Link className="panel-link" to="/profil">Lihat profil dan otorisasi <span>→</span></Link></section></div>
    <section className="panel learning-note"><div className="note-icon">i</div><div><h3>Tarif 12%, hasil efektif 11% — apa bedanya?</h3><p>Untuk nonmewah umum dalam latihan, DPP nilai lain = 11/12 × harga neto. PPN = 12% × DPP nilai lain. Buka rincian faktur untuk menelusuri asal angkanya.</p></div><Link to="/belajar">Pelajari rumus →</Link></section>
  </>;
}
