import { useState } from 'react';
import type { AppState,Role } from '../domain/types';
import { activeRole,type Command } from '../domain/workflow';
import { Badge } from '../components/Ui';

export function Profile({state,dispatch,access=false}:{state:AppState;dispatch:(c:Command)=>void;access?:boolean}){
  const user=state.users.find(u=>u.id===state.actorUserId)!;const wp=state.taxpayers.find(w=>w.id===state.actingTaxpayerId)!;
  const cert=state.certificates.find(c=>c.userId===user.id&&c.status==='ACTIVE');
  const [passphrase,setPassphrase]=useState('');const [error,setError]=useState('');const [assignee,setAssignee]=useState('drafter');const [role,setRole]=useState<Role>('DRAFTER');
  return <><div className="page-header"><div><div className="eyebrow">{access?'MANAJEMEN AKSES':'PORTAL SAYA'}</div><h1>{access?'Pihak terkait & penugasan':'Profil saya'}</h1><p className="muted">Aktor, wajib pajak, dan kewenangan adalah tiga hal yang berbeda.</p></div><Badge kind="blue">DESIGN · kontrol lokal</Badge></div>
    <div className="dashboard-grid"><section className="panel"><div className="panel-title"><h2>Identitas & keamanan demo</h2></div><div className="panel-body"><dl className="identity-list"><div><dt>Aktor</dt><dd>{user.name} ({user.id})</dd></div><div><dt>WP aktif</dt><dd>{wp.name}</dd></div><div><dt>Peran pada WP</dt><dd>{activeRole(state)??'Tanpa penugasan'}</dd></div><div><dt>Akses</dt><dd>{user.activated?'Aktif':'Belum aktif'}</dd></div></dl><label className="check-field"><input type="checkbox" checked={user.twoFactor} onChange={e=>dispatch({type:'SET_TWO_FACTOR',enabled:e.target.checked})}/>Aktifkan 2FA demo untuk login berikutnya</label><p className="hint">OTP latihan selalu <code>123456</code>. Kata sandi latihan <code>Belajar123!</code>. Tidak ada rahasia nyata disimpan.</p></div></section>
    <section className="panel"><div className="panel-title"><h2>Kode Otorisasi DJP demo</h2><Badge kind={cert?'green':'amber'}>{cert?'Aktif · simulasi':'Belum aktif'}</Badge></div><div className="panel-body"><p>Sarana otorisasi latihan harus aktif sebelum signer menandatangani faktur atau menyampaikan SPT.</p><div className="field"><label htmlFor="passphrase">Passphrase demo</label><input id="passphrase" type="password" value={passphrase} onChange={e=>setPassphrase(e.target.value)} placeholder="Gunakan Simulasi123!" autoComplete="off"/><small>Gunakan <code>Simulasi123!</code>. Ini berbeda dari sandi login.</small></div><button className="button primary" disabled={!!cert} onClick={()=>{if(passphrase!=='Simulasi123!'){setError('Passphrase demo harus Simulasi123!.');return;}setError('');dispatch({type:'ACTIVATE_CERTIFICATE'});}}>Aktifkan KODJP demo</button>{error&&<p className="notice error" role="alert">{error}</p>}<p className="hint">Status ini rancangan simulator; tidak menerbitkan sertifikat elektronik yang sah.</p></div></section></div>
    <section className="panel"><div className="panel-title"><h2>Penugasan pada {wp.name}</h2></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Pengguna</th><th>Hubungan</th><th>Role</th><th>Status</th></tr></thead><tbody>{state.assignments.filter(a=>a.taxpayerId===wp.id).map(a=><tr key={a.id}><td>{state.users.find(u=>u.id===a.userId)?.name}</td><td>{state.relatedParties.find(p=>p.userId===a.userId&&p.taxpayerId===wp.id)?.relationship??'Penugasan latihan'}</td><td>{a.role}</td><td>{a.active?'Aktif':'Tidak aktif'}</td></tr>)}</tbody></table></div><div className="panel-body"><div className="form-grid"><div className="field"><label htmlFor="assignee">Pengguna latihan</label><select id="assignee" value={assignee} onChange={e=>setAssignee(e.target.value)}>{state.users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div><div className="field"><label htmlFor="assigned-role">Role yang diberikan</label><select id="assigned-role" value={role} onChange={e=>setRole(e.target.value as Role)}><option value="DRAFTER">Drafter</option><option value="SIGNER">Signer</option><option value="PIC">PIC</option></select></div><div className="field field-action"><button className="button primary" disabled={activeRole(state)!=='PIC'} onClick={()=>dispatch({type:'ASSIGN_ROLE',userId:assignee,taxpayerId:wp.id,role})}>Simpan penugasan</button></div></div><p className="hint">Hanya PIC dapat mengelola penugasan. Drafter boleh menyimpan dan memvalidasi; signer/PIC dengan KODJP demo aktif boleh menandatangani. Pergantian akun melalui pemilih WP adalah latihan impersonate.</p></div></section>
  </>;
}
