import { useCallback, useEffect, useRef, useState } from 'react';
import { Link, NavLink, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import type { AppState, Mode } from './domain/types';
import { activeRole, execute, type Command } from './domain/workflow';
import { createInitialState } from './fixtures/scenarios';
import { loadState, saveState, replaceState } from './storage/store';
import { Login } from './features/Login';
import { Portal } from './features/Portal';
import { Profile } from './features/Profile';
import { Learning } from './features/Learning';
import { Reference, Overview } from './features/Reference';
import { Invoices } from './features/Invoices';
import { Returns } from './features/Returns';
import { Payments } from './features/Payments';

const navigation=[['/','Portal Saya'],['/efaktur','e-Faktur'],['/ebupot','eBupot'],['/spt','SPT'],['/bantuan','Bantuan'],['/pembayaran','Pembayaran'],['/buku-besar','Buku Besar'],['/layanan','Layanan Wajib Pajak'],['/akses','Manajemen Akses'],['/pertukaran','Pertukaran Informasi Perpajakan']];
export default function App(){
  const[state,setState]=useState<AppState|null>(null); const[error,setError]=useState('');const[persistence,setPersistence]=useState('Memuat…');
  const[dark,setDark]=useState(false); const[menu,setMenu]=useState(false); const[toast,setToast]=useState('');
  const stateRef=useRef<AppState|null>(null);const saveCounter=useRef(0);const navigate=useNavigate();const location=useLocation();
  useEffect(()=>{let active=true;void(async()=>{try{let loaded=await loadState();if(!loaded){loaded=createInitialState();await saveState(loaded);}if(active){stateRef.current=loaded;setState(loaded);setPersistence('Tersimpan lokal');}}catch(err){if(active){setError(`Penyimpanan gagal dibuka: ${(err as Error).message}`);const initial=createInitialState();stateRef.current=initial;setState(initial);setPersistence('Belum tersimpan');}}})();return()=>{active=false;};},[]);
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';},[dark]);
  useEffect(()=>{setMenu(false);setError('');},[location.pathname]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer);},[toast]);
  const dispatch=useCallback((command:Command)=>{const current=stateRef.current;if(!current)return;try{const next=execute(current,command);stateRef.current=next;setState(next);setError('');setPersistence('Menyimpan…');const token=++saveCounter.current;const operation=command.type==='RESET'?replaceState(next):saveState(next);void operation.then(()=>{if(token===saveCounter.current)setPersistence('Tersimpan lokal');}).catch(err=>{setError(`Gagal menyimpan progres: ${(err as Error).message}. Ekspor progres sebelum menutup.`);setPersistence('Penyimpanan gagal');});if(command.type==='LOGIN')navigate('/');if(command.type==='LOGOUT'||command.type==='RESET')navigate('/');if(!['LOGIN','LOGOUT','SET_CLOCK','SWITCH_TAXPAYER','SET_MODE'].includes(command.type))setToast('Perubahan latihan dicatat.');}catch(err){setError((err as Error).message);}},[navigate]);
  async function handleImport(next:AppState){await replaceState(next);stateRef.current=next;setState(next);setError('');setPersistence('Tersimpan lokal');}
  const taxAvailable=!!state&&state.taxpayers.some(t=>t.id===state.actingTaxpayerId&&t.type==='PKP')&&!!activeRole(state);
  const common=state?{state,dispatch}:null;
  return <><div className="simulation-banner"><span className="simulation-dot"/>SIMULASI BELAJAR • BUKAN LAYANAN DJP<span className="banner-right">LOKAL · DATA SINTETIS</span></div>
    {!state?<main className="loading-screen"><div className="loading-mark">C</div><p>Menyiapkan ruang latihan…</p></main>:!state.actorUserId?<><Login {...common!} dark={dark} toggleTheme={()=>setDark(!dark)}/>{error&&<div role="alert" className="global-error login-error">{error}<button onClick={()=>setError('')} aria-label="Tutup pesan">×</button></div>}</>:<div className="app-shell">
      <header className="app-header"><Link className="brand" to="/"><span className="brand-icon">C</span><span><b>coretax<span className="brand-light"> learning</span></b><small>SIMULATOR PPN & PPNBM</small></span></Link><div className="header-context"><span className="label-small">BERTINDAK SEBAGAI · IMPERSONATE</span><label className="sr-only" htmlFor="active-taxpayer">Wajib Pajak aktif</label><select id="active-taxpayer" value={state.actingTaxpayerId} onChange={e=>dispatch({type:'SWITCH_TAXPAYER',taxpayerId:e.target.value})}>{state.taxpayers.filter(t=>state.assignments.some(a=>a.active&&a.userId===state.actorUserId&&a.taxpayerId===t.id)).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div className="header-user"><span className="avatar">{state.users.find(u=>u.id===state.actorUserId)?.name.slice(0,1)}</span><span><b>{state.users.find(u=>u.id===state.actorUserId)?.name}</b><small>{activeRole(state)??'Tanpa role'}</small></span><button className="text-button" onClick={()=>dispatch({type:'LOGOUT'})}>Keluar</button></div></header>
      <nav className="global-nav" aria-label="Navigasi utama">{navigation.filter(([path])=>taxAvailable||!['/efaktur','/spt'].includes(path)).map(([path,title])=><NavLink end={path==='/'} to={path} key={path}>{title}{path!=='/'&&<span aria-hidden="true">⌄</span>}</NavLink>)}</nav>
      <div className="workspace"><aside className={`sidebar ${menu?'open':''}`}><div className="sidebar-section">RUANG KERJA</div><NavLink to="/" end><span>▦</span>Ikhtisar</NavLink><NavLink to="/profil"><span>♙</span>Profil & otorisasi</NavLink><div className="sidebar-section">MASA PAJAK PPN</div>{taxAvailable&&<><NavLink to="/efaktur"><span>▤</span>Faktur pajak</NavLink><NavLink to="/spt"><span>▣</span>SPT Masa PPN</NavLink></>}<NavLink to="/pembayaran"><span>▥</span>Pembayaran</NavLink><NavLink to="/buku-besar"><span>▧</span>Buku Besar</NavLink><div className="sidebar-section">PEMBELAJARAN</div><NavLink to="/belajar"><span>◇</span>Latihan & progres</NavLink><NavLink to="/bantuan"><span>ⓘ</span>Referensi & bantuan</NavLink><div className="sidebar-case"><span className="case-dot"/><span><b>{state.scenarioId==='compensation'?'Desember 2026':'Oktober 2026'}</b><small>Kasus sintetis · PKP dagang</small></span></div><div className="sidebar-bottom"><span className="storage-dot"/>{persistence}<small>Semua proses berjalan lokal.</small></div></aside>
      <div className="workspace-main"><div className="context-bar"><div><button className="mobile-menu icon-button" aria-label="Buka menu samping" onClick={()=>setMenu(!menu)}>☰</button><span className="breadcrumb">Coretax Learning <span>/</span> {navigation.find(([p])=>p===location.pathname)?.[1]??(location.pathname==='/belajar'?'Latihan':location.pathname==='/profil'?'Profil':'Ruang kerja')}</span></div><div className="learning-controls"><span className="clock-label">◷ {new Date(state.clock).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric',timeZone:'Asia/Jakarta'})}</span><label className="sr-only" htmlFor="mode">Mode belajar</label><select id="mode" value={state.mode} onChange={e=>dispatch({type:'SET_MODE',mode:e.target.value as Mode})}><option value="TERPANDU">Terpandu</option><option value="MANDIRI">Mandiri</option><option value="UJIAN">Ujian</option></select></div></div>
      <main id="main-content" className="page-content">{error&&<div role="alert" className="global-error"><span>{error}</span><button onClick={()=>setError('')} aria-label="Tutup pesan">×</button></div>}{state.mode==='TERPANDU'&&location.pathname!=='/belajar'&&<div className="guide-strip"><span className="guide-icon">✦</span><span><b>Mode Terpandu</b> · Faktur → Pajak Masukan → Posting SPT → Bayar → Lapor</span><Link to="/belajar">Buka panduan →</Link></div>}
      <Routes><Route path="/" element={<Portal {...common!}/>}/><Route path="/profil" element={<Profile {...common!}/>}/><Route path="/akses" element={<Profile {...common!} access/>}/><Route path="/efaktur/*" element={<>{taxAvailable?<Invoices key={state.actingTaxpayerId} {...common!}/>:<section className="panel"><h1>e-Faktur tidak tersedia</h1><p>WP aktif merupakan profil pribadi non-PKP. Pilih PT Simulasi Niaga Nusantara untuk mengolah faktur PPN. Dokumen milik WP lain tidak ditampilkan.</p></section>}</>}/><Route path="/spt/*" element={<>{taxAvailable?<Returns key={state.actingTaxpayerId} {...common!}/>:<section className="panel"><h1>SPT Masa PPN tidak tersedia</h1><p>Profil WP aktif tidak mempunyai lingkup PKP latihan. Pilih WP badan yang ditugaskan sebelum membuka dokumen PPN.</p></section>}</>}/><Route path="/pembayaran" element={<Payments key={state.actingTaxpayerId} {...common!}/>}/><Route path="/buku-besar" element={<Payments key={state.actingTaxpayerId} {...common!} ledger/>}/><Route path="/belajar" element={<Learning key={`${state.scenarioId}-${state.actorUserId}`} {...common!} onImport={handleImport}/>}/><Route path="/bantuan" element={<Reference state={state}/>}/><Route path="/ebupot" element={<Overview name="eBupot"/>}/><Route path="/layanan" element={<Overview name="PBK & layanan lanjutan"/>}/><Route path="/pertukaran" element={<Overview name="Pertukaran Informasi Perpajakan"/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>
      <footer className="workspace-footer"><span>DESIGN · UI internal mengacu manual DJP beberapa versi; bukan verifikasi produksi.</span><span>Cutoff bukti 04.10.2026 <span className="footer-dot">·</span> v1.0 lokal</span></footer></main></div></div>
    </div>}{toast&&<div role="status" className="toast"><span>✓</span>{toast}</div>}</>;
}
